// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtnbtFSs6WurtmArGQjvm_EKW0ZkeYQOY',
    appId: '1:971823625776:web:4da9be0a9d54952530dff5',
    messagingSenderId: '971823625776',
    projectId: 'integracao-exemplo',
    authDomain: 'integracao-exemplo.firebaseapp.com',
    storageBucket: 'integracao-exemplo.appspot.com',
    measurementId: 'G-1L3K89TQ93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyVlc4esU8jvlaTpx4ITw2J549CtVxpZ8',
    appId: '1:971823625776:android:40228739ac47e9ab30dff5',
    messagingSenderId: '971823625776',
    projectId: 'integracao-exemplo',
    storageBucket: 'integracao-exemplo.appspot.com',
  );
}
